In [1]:
import numpy as np
#importing Numpy for array functionalities

In [5]:
#X =(Hours Studying, Hours Sleeping) y= marks in test
Xa =np.array(([2,9],[1,5],[3,6],[5,10]), dtype=float)
y= np.array(([92],[86],[89]), dtype=float)

In [6]:
#scaling X
Xa=Xa/np.amax(Xa,axis=0)
y=y/100

#splitting the data
X_train=np.split(Xa,[3])[0] #training set of X
X_test=np.split(Xa,[3])[1]  #testset

In [15]:
class Neural_Network(object):
    def __init__(self):
        #parameters for our neural network
        self.inputSize=2
        self.outputSize=1
        self.hiddenSize=3
        
        
        #weights for synapses
        self.W1 =np.random.randn(self.inputSize,self.hiddenSize)  #(3x2) for Input to hidden layer
        self.W2 =np.random.randn(self.hiddenSize,self.outputSize)#(3x1) for hidden to Output layer
    
    
    def forward(self,X_train):
        self.z=np.dot(X_train,self.W1)  #dot product of first set of inputs and weights
        self.z2=self.sigmoid(self.z) #the activation function
        self.z3=np.dot(self.z2,self.W2)  # dot product for last hidden to output layer propogation
        o=self.sigmoid(self.z3)
        return o
    def sigmoid(self,s):
        return 1/(1+np.exp(-s))

NN=Neural_Network()
o=NN.forward(X_train)

print ("Predicted Output: \n" + str(o))
print ("Actual Output: \n" + str(y))

Predicted Output: 
[[0.59235967]
 [0.57620409]
 [0.6091006 ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]


### Hence we need backpropgation here to make or lets say amend things sinceas of now our network kinda sucks actually

#### So here we would select MSE as our Loss Function and rewrite our function completely


In [20]:
class Neural_Network(object):
  def __init__(self):
  #parameters
    self.inputSize = 2
    self.outputSize = 1
    self.hiddenSize = 3

  #weights
    self.W1 = np.random.randn(self.inputSize, self.hiddenSize) # (3x2) weight matrix from input to hidden layer
    self.W2 = np.random.randn(self.hiddenSize, self.outputSize) # (3x1) weight matrix from hidden to output layer

  def forward(self, X_train):
    #forward propagation through our network
    self.z = np.dot(X_train, self.W1) # dot product of X (input) and first set of 3x2 weights
    self.z2 = self.sigmoid(self.z) # activation function
    self.z3 = np.dot(self.z2, self.W2) # dot product of hidden layer (z2) and second set of 3x1 weights
    o = self.sigmoid(self.z3) # final activation function
    return o

  def sigmoid(self, s):
    # activation function
    return 1/(1+np.exp(-s))

  def sigmoidPrime(self, s):
    #derivative of sigmoid
    return s * (1 - s)

  def backward(self, X_train, y, o):
    # backward propagate through the network
    self.o_error = y - o # error in output
    self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to error

    self.z2_error = self.o_delta.dot(self.W2.T) # z2 error: how much our hidden layer weights contributed to output error
    self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) # applying derivative of sigmoid to z2 error

    self.W1 += X_train.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
    self.W2 += self.z2.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights

  def train(self, X_train, y):
    o = self.forward(X_train)
    self.backward(X_train, y, o)

  def saveWeights(self):
    np.savetxt("w1.txt", self.W1, fmt="%s")
    np.savetxt("w2.txt", self.W2, fmt="%s")

  def predict(self):
    print ("Predicted data based on trained weights: ");
    print ("Input (scaled): \n" + str(X_test));
    print ("Output: \n" + str(self.forward(X_test)));

NN = Neural_Network()
for i in range(1000): # trains the NN 1,000 times
  print ("# " + str(i) + "\n")
  print ("Input (scaled): \n" + str(X_train))
  print ("Actual Output: \n" + str(y))
  print ("Predicted Output: \n" + str(NN.forward(X_train)))
  print ("Loss: \n" + str(np.mean(np.square(y - NN.forward(X_train))))) # mean sum squared loss
  print ("\n")
  NN.train(X_train, y)

NN.saveWeights()
NN.predict()

# 0

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.40176047]
 [0.32627507]
 [0.38697743]]
Loss: 
0.2688220706534921


# 1

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.49979621]
 [0.40694964]
 [0.48484625]]
Loss: 
0.18199180748841123


# 2

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.58198968]
 [0.47961677]
 [0.56825082]]
Loss: 
0.1208216386736825


# 3

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.64393933]
 [0.5382557 ]
 [0.63176765]]
Loss: 
0.08213761336161855


# 4

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.6892577 ]
 [0.58369091]
 [0.67850523]]
Loss: 
0.05810625474881209


# 5

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual